### PR TITLE
fix(style): Returned .text-input-component-disabled style

### LINKED ISSUE #50: Return style: .text-input-component-disabled
It should help distinguish disabled and not disabled components

### PR DESCRIPTION
**Pull request by Lyams**
Closes #50.

- [x] I have reviewed my code in "Files changed" tab.
- [x] I have re-read the issue and this PR fully resolves it.

### CODE REVIEW

**Comment by ksnitsky** [comment]
It looks too dark, you can't see the borders and the text color is plain.
image


@delavaler Are we sure we want to return these styles and not use the default ones from tabler?
cc @amgalanbadmaev
image

**Review by ksnitsky — COMMENTED** [review]
Add `:focus` style to a default `.form-control:disabled`, `.form-control.disabled` class

**Comment by ksnitsky** [comment]
@amgalanbadmaev should the `disabled` and `readonly` fields looks the same?

The old styles assumed that the text color would be the same as a normal input field, but with a `gray-200` background.
So `readonly` will have the normal color, `gray-100` background (tabler style), focus style and the ability to select text
And `disabled` would have the same `gray-100` background, but no text selection, no focus style and a text color of `gray-500`.
Are we fine with this changes?

image

**Comment by amgalanbadmaev** [comment]
Yes, all correct

**Comment by ksnitsky** [comment]
> Yes, all correct. We also using tabler's color for disabled text color, right?

Yes `gray-500` (the top input field in the screenshot)

**Pull request merged**
