### PR TITLE
feat: new error pages

### LINKED ISSUE #165: Errors styles update
**Problem**
We want to further move to Tabler’s design in our UI. This time let’s update our Error pages.

**Solution**
Mockups: [Figma](https://www.figma.com/design/kQOH4s5DnfWL0p6o6tlMQz/Draft-%5BATS%5D?node-id=1595-12985&t=gHIyxtD5okLIYo8B-1)

After we push migration-to-tabler branch style changes to production, apply these changes to Error pages:

403 page
--------

- Container:
  - Set 48px paddings for all sides (as in [Tabler](https://preview.tabler.io/blank.html))
  - But keep page container paddings as is (24px top&side, 48px bottom paddings)
  - Align content within to center horizontally
  - Set spacing between elements within as on mockups

- Error code:
  - "403" text
  - Set font-styles as in [Tabler](https://preview.tabler.io/error-500.html) (64px font-size; 64px line-height; font-weight 300; #6C7A91 color)

- Heading:
  - "Forbidden" text
  - 20px font-size, 32px line-height, font-weight 600, #182433 color

- Text:
  - "You don't have permission to access this page."
  - 14px font-size, 1.5 line-height, font-weight 400, #6C7A91 color

- Button:
  - label "Take me home"
  - on click should redirect to app root (e.g. app.freeats.com)
  - style Primary, size Small, [arrow-left](https://tabler.io/icons/icon/arrow-left) icon (stroke-width 1.25; 17x17px size)

404 page
--------

-   Update container as described above

-   Error code: 404

-   Heading: "Not found"

-   Text: "The page you were looking for doesn't exist."

-   Button as described above

422 page
--------

-   Update container as described above

-   Error code: 422

-   Heading: "Unprocessable content"

-   Text: "We couldn't process your request because some information is missing or incorrect."

-   Button as described above

500 page
--------

-   Update container as described above

-   Error code: 500

-   Heading: "Internal server error"

-   Text: "Something went wrong, please try again later."

-   Button as described above

### PR DESCRIPTION
**Pull request by ksnitsky**
Closes #165.

- [x] I have reviewed my code in "Files changed" tab.
- [x] I have re-read the issue and this PR fully resolves it.

### CODE REVIEW

**Review by ksnitsky — COMMENTED** [review]
I haven't figured out how to quickly unify the 403, 404, and 422 pages

**Review by wrmk — APPROVED** [review]
nitpick: is it possible to fix this little jumping for 500 error?

https://github.com/user-attachments/assets/6083fc54-5089-427c-8380-6c5a4a05d35e

**Comment by ksnitsky** [comment]
> nitpick: is it possible to fix this little jumping for 500 error?
> simplescreenrecorder-2024-11-19_08.34.39.mp4

That's how I discovered the navbar variable bug https://github.com/freeats/freeats/pull/214

**Comment by wrmk** [comment]
> > nitpick: is it possible to fix this little jumping for 500 error?
> > simplescreenrecorder-2024-11-19_08.34.39.mp4
> 
> That's how I discovered the navbar variable bug #214

so this jumping already fixed on prod?

**Comment by wrmk** [comment]
I see, fixed

**Comment by wrmk** [comment]
@ksnitsky for some reason arrow left brigther on 500 error
image
image

**Comment by ksnitsky** [comment]
> @ksnitsky for some reason arrow left brigther on 500 error image image

image
Because of the standard icon style

Didn't notice it, I'll fix

**Pull request merged**
